### ISSUE TITLE
HasLink for RawM'

### ISSUE THREAD

**Issue by amesgen** [cdepillabout/servant-rawm#11]
It would be nice to have a `HasLink` instance for `RawM'` like this:
```haskell
instance HasLink (RawM' st) where
  type MkLink (RawM' st) a = a
  toLink toA _ = toA
```
I can create a PR but I am not sure where to put the instance into your module structure.

**Comment by cdepillabout** [comment]
@amesgen Thanks for the suggestion.  If you create a PR I will merge it in.

`HasLink` is provided by the `servant` package itself, right?  I guess it should probably go in https://github.com/cdepillabout/servant-rawm/blob/master/src/Servant/RawM/Internal/API.hs.
