### ISSUE TITLE
Move client and docs to separate packages?

### ISSUE THREAD

**Issue by Krasjet** [cdepillabout/servant-rawm#14]
Hello,

Thank you for making this package. I noticed that this package introduces a ton of extra dependencies to my application since it depends on servant-client and servant-docs, and servant-docs depends on lens.

I might suggest separating these components to servant-rawm-client and servant-rawm-docs, respectively, since they are not necessary to build a server application and can significantly increase the build time.

Best,
kst.

**Comment by cdepillabout** [comment]
This sounds good.

I'd be happy to merge a PR implementing something like this.  Ideally the packages would mirror the structure of the normal `servant` packages.

**Comment by Krasjet** [comment]
Work in progress at https://github.com/Krasjet/servant-rawm

**Comment by cdepillabout** [comment]
@Krasjet Thanks for working on this!

**Comment by cdepillabout** [comment]
This was merged in #15.  This will be released to hackage as a few different packages:

- servant-rawm
- servant-rawm-client
- servant-rawm-docs
- servant-rawm-server

This mirrors the layout of the actual `servant` packages.
