### ISSUE TITLE
Upload 1.0.0.2 to hackage

### ISSUE THREAD

**Issue by Profpatsch** [cdepillabout/servant-rawm#22]
There was a bump, but apparently the release on hackage was forgotten.

**Comment by cdepillabout** [comment]
If I remember correctly, only `servant-rawm-client` needed the bump: https://hackage.haskell.org/package/servant-rawm-client-1.0.0.2 

The latest versions of `servant-rawm` packages should all work with it.

Although it is confusing that they have slightly different version numbers.  If you wanted to add an explanation about this (or even like a table with the current latest compatible version numbers) to the README, I'd likely accept it.

**Comment by Profpatsch** [comment]
What about `servant-rawm-server`?

**Comment by cdepillabout** [comment]
The latest version of `servant-rawm-server` is 1.0.0.1, and it is on Hackage: https://hackage.haskell.org/package/servant-rawm-server-1.0.0.1
