### ISSUE TITLE
Not available on stackage

### ISSUE THREAD

**Issue by xaviershay** [cdepillabout/servant-rawm#8]
Thank you for making this package! I had to add `servant-rawm` to my `extra-deps` to use it though, which makes me uncomfortable.

Sorry I'm not familiar enough with stack yet to know what would have to happen to get this library included.

**Comment by cdepillabout** [comment]
@xaviershay Sorry, I think I just let it slip out of stackage.

If you want to open a pull request on the stackage repo adding it back in (I guess under `cdepillabout`), I'd really appreciate it.

If `servant-rawm` no longer compiles under LTS-12 (or nightly), then feel free to either open an issue here or send a PR updating `servant-rawm` so it compiles.

**Comment by cdepillabout** [comment]
This should be closed by https://github.com/commercialhaskell/stackage/pull/4768.

**Comment by cdepillabout** [comment]
`servant-rawm` should be available in stackage nightly, as well as LTS-14.4:

https://github.com/commercialhaskell/stackage/pull/4768

https://github.com/commercialhaskell/lts-haskell/issues/242
